"""create companies and company_brain_profiles tables

Revision ID: a505cda518bb
Revises: 0002_enable_pgvector
Create Date: 2026-08-22 22:17:09.829787

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a505cda518bb'
down_revision: Union[str, None] = '0002_enable_pgvector'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('company_brain_profiles',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('strategy', sa.String(), nullable=True),
    sa.Column('non_goals', sa.String(), nullable=True),
    sa.Column('current_priorities', sa.String(), nullable=True),
    sa.Column('current_bottlenecks', sa.String(), nullable=True),
    sa.Column('working_style', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id'),
    sa.UniqueConstraint('company_id', name='uq_company_brain_profiles_company_id')
    )
    op.create_index('ix_company_brain_profiles_company_id', 'company_brain_profiles', ['company_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_company_brain_profiles_company_id', table_name='company_brain_profiles')
    op.drop_table('company_brain_profiles')
    op.drop_table('companies')
    # ### end Alembic commands ###
