"""create all task 2 database tables

Revision ID: f2c24b6a4279
Revises: a505cda518bb
Create Date: 2026-08-22 23:00:39.238018

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = 'f2c24b6a4279'
down_revision: Union[str, None] = 'a505cda518bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('email', name='uq_users_email')
    )
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_table('company_beliefs',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('statement', sa.String(), nullable=False),
    sa.Column('reasoning', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_company_beliefs_company_id', 'company_beliefs', ['company_id'], unique=False)
    op.create_index('ix_company_beliefs_company_id_status', 'company_beliefs', ['company_id', 'status'], unique=False)
    op.create_table('company_constraints',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_company_constraints_company_id', 'company_constraints', ['company_id'], unique=False)
    op.create_index('ix_company_constraints_company_id_status', 'company_constraints', ['company_id', 'status'], unique=False)
    op.create_table('company_facts',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('value_type', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('source_reference', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('observed_at', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_company_facts_company_id', 'company_facts', ['company_id'], unique=False)
    op.create_index('ix_company_facts_company_id_status', 'company_facts', ['company_id', 'status'], unique=False)
    op.create_table('company_members',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'user_id', name='uq_company_members_company_user')
    )
    op.create_index('ix_company_members_company_id', 'company_members', ['company_id'], unique=False)
    op.create_index('ix_company_members_user_id', 'company_members', ['user_id'], unique=False)
    op.create_table('evidence',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('source_reference', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('observed_at', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_evidence_company_id', 'evidence', ['company_id'], unique=False)
    op.create_index('ix_evidence_company_id_created_at', 'evidence', ['company_id', 'created_at'], unique=False)
    op.create_table('integrations',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('integration_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('scopes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_integrations_company_id', 'integrations', ['company_id'], unique=False)
    op.create_index('ix_integrations_company_id_status', 'integrations', ['company_id', 'status'], unique=False)
    op.create_table('memories',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('memory_type', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('source_reference', sa.String(), nullable=True),
    sa.Column('importance', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_memories_company_id', 'memories', ['company_id'], unique=False)
    op.create_index('ix_memories_company_id_created_at', 'memories', ['company_id', 'created_at'], unique=False)
    op.create_table('metrics',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('target_value', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_metrics_company_id', 'metrics', ['company_id'], unique=False)
    op.create_table('objectives',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('target_value', sa.String(), nullable=True),
    sa.Column('target_unit', sa.String(), nullable=True),
    sa.Column('deadline', sa.String(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_objectives_company_id', 'objectives', ['company_id'], unique=False)
    op.create_index('ix_objectives_company_id_created_at', 'objectives', ['company_id', 'created_at'], unique=False)
    op.create_index('ix_objectives_company_id_status', 'objectives', ['company_id', 'status'], unique=False)
    op.create_table('agent_runs',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('agent_type', sa.String(), nullable=False),
    sa.Column('objective_id', sa.UUID(), nullable=True),
    sa.Column('task_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('model_provider', sa.String(), nullable=True),
    sa.Column('model_name', sa.String(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('estimated_cost', sa.Float(), nullable=True),
    sa.Column('started_at', sa.String(), nullable=True),
    sa.Column('completed_at', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('trace_id', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['objective_id'], ['objectives.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_runs_company_id', 'agent_runs', ['company_id'], unique=False)
    op.create_index('ix_agent_runs_company_id_status', 'agent_runs', ['company_id', 'status'], unique=False)
    op.create_index('ix_agent_runs_objective_id', 'agent_runs', ['objective_id'], unique=False)
    op.create_table('decisions',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('objective_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('decision', sa.String(), nullable=False),
    sa.Column('rationale', sa.String(), nullable=False),
    sa.Column('expected_outcome', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['objective_id'], ['objectives.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_decisions_company_id', 'decisions', ['company_id'], unique=False)
    op.create_index('ix_decisions_company_id_status', 'decisions', ['company_id', 'status'], unique=False)
    op.create_index('ix_decisions_objective_id', 'decisions', ['objective_id'], unique=False)
    op.create_table('hypotheses',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('objective_id', sa.UUID(), nullable=False),
    sa.Column('statement', sa.String(), nullable=False),
    sa.Column('reasoning', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['objective_id'], ['objectives.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_hypotheses_company_id', 'hypotheses', ['company_id'], unique=False)
    op.create_index('ix_hypotheses_company_id_status', 'hypotheses', ['company_id', 'status'], unique=False)
    op.create_index('ix_hypotheses_objective_id', 'hypotheses', ['objective_id'], unique=False)
    op.create_table('metric_observations',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('metric_id', sa.UUID(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('observed_at', sa.String(), nullable=False),
    sa.Column('source_reference', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['metric_id'], ['metrics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_metric_observations_company_id', 'metric_observations', ['company_id'], unique=False)
    op.create_index('ix_metric_observations_metric_id', 'metric_observations', ['metric_id'], unique=False)
    op.create_table('experiments',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('objective_id', sa.UUID(), nullable=False),
    sa.Column('hypothesis_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('method', sa.String(), nullable=True),
    sa.Column('primary_metric', sa.String(), nullable=True),
    sa.Column('target_value', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.String(), nullable=True),
    sa.Column('ended_at', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hypothesis_id'], ['hypotheses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['objective_id'], ['objectives.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_experiments_company_id', 'experiments', ['company_id'], unique=False)
    op.create_index('ix_experiments_company_id_status', 'experiments', ['company_id', 'status'], unique=False)
    op.create_index('ix_experiments_objective_id', 'experiments', ['objective_id'], unique=False)
    op.create_table('objective_tasks',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('objective_id', sa.UUID(), nullable=False),
    sa.Column('hypothesis_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('capability', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('assigned_agent', sa.String(), nullable=True),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.String(), nullable=True),
    sa.Column('completed_at', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hypothesis_id'], ['hypotheses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['objective_id'], ['objectives.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_objective_tasks_company_id', 'objective_tasks', ['company_id'], unique=False)
    op.create_index('ix_objective_tasks_company_id_status', 'objective_tasks', ['company_id', 'status'], unique=False)
    op.create_index('ix_objective_tasks_objective_id', 'objective_tasks', ['objective_id'], unique=False)
    op.create_table('agent_tasks',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('agent_run_id', sa.UUID(), nullable=True),
    sa.Column('objective_task_id', sa.UUID(), nullable=True),
    sa.Column('agent_type', sa.String(), nullable=False),
    sa.Column('task_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('input', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('started_at', sa.String(), nullable=True),
    sa.Column('completed_at', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['objective_task_id'], ['objective_tasks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_tasks_agent_run_id', 'agent_tasks', ['agent_run_id'], unique=False)
    op.create_index('ix_agent_tasks_company_id', 'agent_tasks', ['company_id'], unique=False)
    op.create_index('ix_agent_tasks_company_id_status', 'agent_tasks', ['company_id', 'status'], unique=False)
    op.create_table('experiment_results',
    sa.Column('experiment_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('metric_name', sa.String(), nullable=False),
    sa.Column('baseline_value', sa.String(), nullable=True),
    sa.Column('result_value', sa.String(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('interpretation', sa.String(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('evidence_id', sa.UUID(), nullable=True),
    sa.Column('recorded_at', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_experiment_results_company_id', 'experiment_results', ['company_id'], unique=False)
    op.create_index('ix_experiment_results_experiment_id', 'experiment_results', ['experiment_id'], unique=False)
    op.create_table('learnings',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('objective_id', sa.UUID(), nullable=True),
    sa.Column('experiment_id', sa.UUID(), nullable=True),
    sa.Column('statement', sa.String(), nullable=False),
    sa.Column('evidence_summary', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['objective_id'], ['objectives.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_learnings_company_id', 'learnings', ['company_id'], unique=False)
    op.create_index('ix_learnings_company_id_status', 'learnings', ['company_id', 'status'], unique=False)
    op.create_index('ix_learnings_objective_id', 'learnings', ['objective_id'], unique=False)
    op.create_table('approvals',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('agent_task_id', sa.UUID(), nullable=True),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('risk_level', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('requested_at', sa.String(), nullable=False),
    sa.Column('resolved_at', sa.String(), nullable=True),
    sa.Column('resolved_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['agent_task_id'], ['agent_tasks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_approvals_agent_task_id', 'approvals', ['agent_task_id'], unique=False)
    op.create_index('ix_approvals_company_id', 'approvals', ['company_id'], unique=False)
    op.create_index('ix_approvals_company_id_status', 'approvals', ['company_id', 'status'], unique=False)
    op.create_table('artifacts',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('agent_task_id', sa.UUID(), nullable=True),
    sa.Column('artifact_type', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('storage_uri', sa.String(), nullable=True),
    sa.Column('mime_type', sa.String(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['agent_task_id'], ['agent_tasks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_artifacts_agent_task_id', 'artifacts', ['agent_task_id'], unique=False)
    op.create_index('ix_artifacts_company_id', 'artifacts', ['company_id'], unique=False)
    op.add_column('companies', sa.Column('name', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('slug', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('mission', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('vision', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('product_description', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('target_customer', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('stage', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('companies', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index('ix_companies_slug', 'companies', ['slug'], unique=False)
    op.create_unique_constraint('uq_companies_slug', 'companies', ['slug'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_companies_slug', 'companies', type_='unique')
    op.drop_index('ix_companies_slug', table_name='companies')
    op.drop_column('companies', 'updated_at')
    op.drop_column('companies', 'created_at')
    op.drop_column('companies', 'stage')
    op.drop_column('companies', 'target_customer')
    op.drop_column('companies', 'product_description')
    op.drop_column('companies', 'vision')
    op.drop_column('companies', 'mission')
    op.drop_column('companies', 'slug')
    op.drop_column('companies', 'name')
    op.drop_index('ix_artifacts_company_id', table_name='artifacts')
    op.drop_index('ix_artifacts_agent_task_id', table_name='artifacts')
    op.drop_table('artifacts')
    op.drop_index('ix_approvals_company_id_status', table_name='approvals')
    op.drop_index('ix_approvals_company_id', table_name='approvals')
    op.drop_index('ix_approvals_agent_task_id', table_name='approvals')
    op.drop_table('approvals')
    op.drop_index('ix_learnings_objective_id', table_name='learnings')
    op.drop_index('ix_learnings_company_id_status', table_name='learnings')
    op.drop_index('ix_learnings_company_id', table_name='learnings')
    op.drop_table('learnings')
    op.drop_index('ix_experiment_results_experiment_id', table_name='experiment_results')
    op.drop_index('ix_experiment_results_company_id', table_name='experiment_results')
    op.drop_table('experiment_results')
    op.drop_index('ix_agent_tasks_company_id_status', table_name='agent_tasks')
    op.drop_index('ix_agent_tasks_company_id', table_name='agent_tasks')
    op.drop_index('ix_agent_tasks_agent_run_id', table_name='agent_tasks')
    op.drop_table('agent_tasks')
    op.drop_index('ix_objective_tasks_objective_id', table_name='objective_tasks')
    op.drop_index('ix_objective_tasks_company_id_status', table_name='objective_tasks')
    op.drop_index('ix_objective_tasks_company_id', table_name='objective_tasks')
    op.drop_table('objective_tasks')
    op.drop_index('ix_experiments_objective_id', table_name='experiments')
    op.drop_index('ix_experiments_company_id_status', table_name='experiments')
    op.drop_index('ix_experiments_company_id', table_name='experiments')
    op.drop_table('experiments')
    op.drop_index('ix_metric_observations_metric_id', table_name='metric_observations')
    op.drop_index('ix_metric_observations_company_id', table_name='metric_observations')
    op.drop_table('metric_observations')
    op.drop_index('ix_hypotheses_objective_id', table_name='hypotheses')
    op.drop_index('ix_hypotheses_company_id_status', table_name='hypotheses')
    op.drop_index('ix_hypotheses_company_id', table_name='hypotheses')
    op.drop_table('hypotheses')
    op.drop_index('ix_decisions_objective_id', table_name='decisions')
    op.drop_index('ix_decisions_company_id_status', table_name='decisions')
    op.drop_index('ix_decisions_company_id', table_name='decisions')
    op.drop_table('decisions')
    op.drop_index('ix_agent_runs_objective_id', table_name='agent_runs')
    op.drop_index('ix_agent_runs_company_id_status', table_name='agent_runs')
    op.drop_index('ix_agent_runs_company_id', table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_index('ix_objectives_company_id_status', table_name='objectives')
    op.drop_index('ix_objectives_company_id_created_at', table_name='objectives')
    op.drop_index('ix_objectives_company_id', table_name='objectives')
    op.drop_table('objectives')
    op.drop_index('ix_metrics_company_id', table_name='metrics')
    op.drop_table('metrics')
    op.drop_index('ix_memories_company_id_created_at', table_name='memories')
    op.drop_index('ix_memories_company_id', table_name='memories')
    op.drop_table('memories')
    op.drop_index('ix_integrations_company_id_status', table_name='integrations')
    op.drop_index('ix_integrations_company_id', table_name='integrations')
    op.drop_table('integrations')
    op.drop_index('ix_evidence_company_id_created_at', table_name='evidence')
    op.drop_index('ix_evidence_company_id', table_name='evidence')
    op.drop_table('evidence')
    op.drop_index('ix_company_members_user_id', table_name='company_members')
    op.drop_index('ix_company_members_company_id', table_name='company_members')
    op.drop_table('company_members')
    op.drop_index('ix_company_facts_company_id_status', table_name='company_facts')
    op.drop_index('ix_company_facts_company_id', table_name='company_facts')
    op.drop_table('company_facts')
    op.drop_index('ix_company_constraints_company_id_status', table_name='company_constraints')
    op.drop_index('ix_company_constraints_company_id', table_name='company_constraints')
    op.drop_table('company_constraints')
    op.drop_index('ix_company_beliefs_company_id_status', table_name='company_beliefs')
    op.drop_index('ix_company_beliefs_company_id', table_name='company_beliefs')
    op.drop_table('company_beliefs')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
